include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    directives_ordering: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_constructors_first: true
    unawaited_futures: true
