// Mocks generated by Mockito 5.4.6 from annotations
// in tictactoe/testing/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:tictactoe/core/storage/key_value_storage.dart' as _i15;
import 'package:tictactoe/features/game/domain/entities/app_preferences.dart'
    as _i2;
import 'package:tictactoe/features/game/domain/entities/board.dart' as _i13;
import 'package:tictactoe/features/game/domain/entities/game_audio_settings.dart'
    as _i10;
import 'package:tictactoe/features/game/domain/entities/game_result.dart'
    as _i18;
import 'package:tictactoe/features/game/domain/entities/menu_sfx.dart' as _i8;
import 'package:tictactoe/features/game/domain/entities/music_track.dart'
    as _i7;
import 'package:tictactoe/features/game/domain/entities/player.dart' as _i14;
import 'package:tictactoe/features/game/domain/entities/scoreboard.dart' as _i3;
import 'package:tictactoe/features/game/domain/repositories/app_preferences_repository.dart'
    as _i4;
import 'package:tictactoe/features/game/domain/repositories/audio_settings_repository.dart'
    as _i9;
import 'package:tictactoe/features/game/domain/repositories/scoreboard_repository.dart'
    as _i17;
import 'package:tictactoe/features/game/domain/services/audio_controller.dart'
    as _i6;
import 'package:tictactoe/features/game/domain/services/cpu_strategy.dart'
    as _i12;
import 'package:tictactoe/features/game/domain/services/music_player.dart'
    as _i16;
import 'package:tictactoe/features/game/domain/services/sfx_player.dart'
    as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppPreferences_0 extends _i1.SmartFake
    implements _i2.AppPreferences {
  _FakeAppPreferences_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeScoreboard_1 extends _i1.SmartFake implements _i3.Scoreboard {
  _FakeScoreboard_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppPreferencesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppPreferencesRepository extends _i1.Mock
    implements _i4.AppPreferencesRepository {
  @override
  _i5.Future<_i2.AppPreferences> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i5.Future<_i2.AppPreferences>.value(
              _FakeAppPreferences_0(this, Invocation.method(#load, [])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.AppPreferences>.value(
              _FakeAppPreferences_0(this, Invocation.method(#load, [])),
            ),
          )
          as _i5.Future<_i2.AppPreferences>);

  @override
  _i5.Future<void> save(_i2.AppPreferences? preferences) =>
      (super.noSuchMethod(
            Invocation.method(#save, [preferences]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [AudioController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioController extends _i1.Mock implements _i6.AudioController {
  @override
  _i5.Future<void> playTrack(_i7.MusicTrack? track) =>
      (super.noSuchMethod(
            Invocation.method(#playTrack, [track]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> prepareGame() =>
      (super.noSuchMethod(
            Invocation.method(#prepareGame, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> playMenuSfx(_i8.MenuSfx? intent) =>
      (super.noSuchMethod(
            Invocation.method(#playMenuSfx, [intent]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> pauseMusic() =>
      (super.noSuchMethod(
            Invocation.method(#pauseMusic, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> stopMusic() =>
      (super.noSuchMethod(
            Invocation.method(#stopMusic, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void setMusicEnabled(bool? enabled) => super.noSuchMethod(
    Invocation.method(#setMusicEnabled, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  void setSfxEnabled(bool? enabled) => super.noSuchMethod(
    Invocation.method(#setSfxEnabled, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  void setMusicVolume(double? volume) => super.noSuchMethod(
    Invocation.method(#setMusicVolume, [volume]),
    returnValueForMissingStub: null,
  );

  @override
  void setSfxVolume(double? volume) => super.noSuchMethod(
    Invocation.method(#setSfxVolume, [volume]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> playMove({required bool? isPlayerX}) =>
      (super.noSuchMethod(
            Invocation.method(#playMove, [], {#isPlayerX: isPlayerX}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> playParry() =>
      (super.noSuchMethod(
            Invocation.method(#playParry, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> playVictory() =>
      (super.noSuchMethod(
            Invocation.method(#playVictory, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> playDeathIntro() =>
      (super.noSuchMethod(
            Invocation.method(#playDeathIntro, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> playDeath() =>
      (super.noSuchMethod(
            Invocation.method(#playDeath, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> playDraw() =>
      (super.noSuchMethod(
            Invocation.method(#playDraw, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> playRestart() =>
      (super.noSuchMethod(
            Invocation.method(#playRestart, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [AudioSettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioSettingsRepository extends _i1.Mock
    implements _i9.AudioSettingsRepository {
  @override
  _i5.Future<_i10.GameAudioSettings> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i5.Future<_i10.GameAudioSettings>.value(
              _i11.dummyValue<_i10.GameAudioSettings>(
                this,
                Invocation.method(#load, []),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i10.GameAudioSettings>.value(
              _i11.dummyValue<_i10.GameAudioSettings>(
                this,
                Invocation.method(#load, []),
              ),
            ),
          )
          as _i5.Future<_i10.GameAudioSettings>);

  @override
  _i5.Future<void> save(_i10.GameAudioSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#save, [settings]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [CpuStrategy].
///
/// See the documentation for Mockito's code generation for more information.
class MockCpuStrategy extends _i1.Mock implements _i12.CpuStrategy {
  @override
  int chooseMove(_i13.Board? board, _i14.Player? player) =>
      (super.noSuchMethod(
            Invocation.method(#chooseMove, [board, player]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);
}

/// A class which mocks [KeyValueStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyValueStorage extends _i1.Mock implements _i15.KeyValueStorage {
  @override
  _i5.Future<String?> readString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#readString, [key]),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> writeString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#writeString, [key, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [MusicPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockMusicPlayer extends _i1.Mock implements _i16.MusicPlayer {
  @override
  _i5.Future<void> play(
    String? asset, {
    required double? targetVolume,
    Duration? transitionDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #play,
              [asset],
              {
                #targetVolume: targetVolume,
                #transitionDuration: transitionDuration,
              },
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> prepare(String? asset) =>
      (super.noSuchMethod(
            Invocation.method(#prepare, [asset]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> pause({Duration? fadeDuration}) =>
      (super.noSuchMethod(
            Invocation.method(#pause, [], {#fadeDuration: fadeDuration}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> stop({Duration? fadeDuration}) =>
      (super.noSuchMethod(
            Invocation.method(#stop, [], {#fadeDuration: fadeDuration}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ScoreboardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockScoreboardRepository extends _i1.Mock
    implements _i17.ScoreboardRepository {
  @override
  _i5.Future<_i3.Scoreboard> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i5.Future<_i3.Scoreboard>.value(
              _FakeScoreboard_1(this, Invocation.method(#load, [])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Scoreboard>.value(
              _FakeScoreboard_1(this, Invocation.method(#load, [])),
            ),
          )
          as _i5.Future<_i3.Scoreboard>);

  @override
  _i5.Future<void> save(_i3.Scoreboard? scoreboard) =>
      (super.noSuchMethod(
            Invocation.method(#save, [scoreboard]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.Scoreboard> record(_i18.GameOutcome? outcome) =>
      (super.noSuchMethod(
            Invocation.method(#record, [outcome]),
            returnValue: _i5.Future<_i3.Scoreboard>.value(
              _FakeScoreboard_1(this, Invocation.method(#record, [outcome])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Scoreboard>.value(
              _FakeScoreboard_1(this, Invocation.method(#record, [outcome])),
            ),
          )
          as _i5.Future<_i3.Scoreboard>);

  @override
  _i5.Future<void> reset() =>
      (super.noSuchMethod(
            Invocation.method(#reset, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SfxPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockSfxPlayer extends _i1.Mock implements _i19.SfxPlayer {
  @override
  _i5.Future<void> play(String? asset, {required double? volume}) =>
      (super.noSuchMethod(
            Invocation.method(#play, [asset], {#volume: volume}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> warmUp(Iterable<String>? assets) =>
      (super.noSuchMethod(
            Invocation.method(#warmUp, [assets]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
